Thread functions
t-vinn/rails-bbs-without-scaffold pull request #5
Opened 2017-01-28 10:26 UTC by t-vinn

まだコメントがないので詳細表示のviewは作り込んでません。
スレッドの作成削除編集はできます。
スレッド名はblankだとはじかれます。
リダイレクトができてはいるものの適切ではない（別のとこにリダイレクトした方が使いやすい）かもしれません。

2017-01-28 11:15 UTC, MihoSasaki requested changes
reviewed

2017-01-28 11:15 UTC, MihoSasaki commented on app/controllers/my_threads_controller.rb
> +
controllerにログインしてないとaccessできないようにしてほしい。
あとログインできないばあいはredirectしてログイン画面に遷移されるように
(login状態かどうかを判別できるmethodをapplication_helperとかに持っとくとすっきりするはず)

2017-01-28 11:15 UTC, MihoSasaki commented on app/models/my_thread.rb
> +  validates :title, presence: true
基本全てのカラムに対してvalidateする。
(nits) 字数制限できるようにしてみよう
あとUserモデルとの関係はどうなってるんだっけ？

2017-01-28 11:15 UTC, MihoSasaki commented on app/views/my_threads/index.html.erb
> +        <td><%= link_to 'edit', edit_my_thread_path(my_thread) %></td>
自分以外のuserが作ったものは編集・削除できないようにする

2017-01-28 11:15 UTC, MihoSasaki commented on app/controllers/my_threads_controller.rb
> +    @my_threads = MyThread.all
(nits)若干myがついていると自分が作ったthreadのみって感じがするので@threadsとかのほうがいい感じがする。。

2017-01-28 11:15 UTC, MihoSasaki commented on app/controllers/my_threads_controller.rb
> +    flash.now[:notice] = "a thread correctly deleted"
削除できなかったらどうする？

2017-01-28 11:16 UTC, MihoSasaki commented
Userモデルもきちんと書こう

2017-01-29 03:14 UTC, t-vinn commented on app/models/my_thread.rb
> +  validates :title, presence: true
スレッドに関してはtitleしか情報がないので、とりあえずtitleだけvalidateしました

2017-01-30 00:57 UTC, MihoSasaki approved these changes
reviewed

2017-01-30 01:54 UTC, merged